const assert=require('assert');
const {Match2DEngine}=require('./match2d-engine.js');
const {HistoricalDecisionBridge}=require('./decision-bridge.js');
const engine=new Match2DEngine({tickMs:999999});
const bridge=new HistoricalDecisionBridge(engine);
const scenario={kind:'tactical',t:'Test',d:'Pending',o:[{t:'Presionar la salida',h:'x',e:{att:.018,def:-.006},set:'pressHigh'}]};
const before=JSON.stringify(scenario);
assert.equal(bridge.pauseForScenario(scenario),true);
assert.equal(engine.state.paused,true);
assert.equal(JSON.stringify(scenario),before,'bridge must not mutate historical scenario');
assert.equal(bridge.pendingScenario,scenario,'same scenario reference remains pending');
bridge.mirrorChoice(0,'home');
assert.equal(engine.state.tactics.home.press,1,'visual tactic applied');
assert.equal(JSON.stringify(scenario),before,'visual mirror must not mutate historical scenario');
bridge.pendingScenario=scenario;
const r=bridge.failVisualOnly(new Error('forced visual failure'));
assert.equal(r.scenarioStillPending,true,'visual failure must not consume pending historical scenario');
assert.equal(bridge.pendingScenario,scenario,'pending scenario survives visual failure');
engine.stop();
console.log('Match2D smoke test OK');
