/* ===== El Míster v0.8.0 · nuevo motor 2D de partido (Canvas) ===== */
(function(){
  const st=document.createElement('style');
  st.textContent=`
  .em80MatchBg{background:rgba(2,7,11,.95);align-items:center;padding:8px}.em80MatchBg .modal{width:min(548px,100%);max-height:calc(100vh - 16px);overflow:auto;background:#07131b;border:1px solid #294657;padding:12px;border-radius:22px}
  .em80Top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;margin-bottom:9px}.em80Minute{font-size:10px;font-weight:950;color:var(--gold);letter-spacing:.08em}.em80Score{font-size:34px;font-weight:1000;line-height:1;margin-top:2px}.em80Teams{font-size:10px;color:var(--muted);margin-top:4px}.em80Mode{font-size:9px;border:1px solid rgba(85,214,147,.3);background:rgba(85,214,147,.08);color:#b7f0d0;border-radius:999px;padding:5px 8px;white-space:nowrap}
  .em80CanvasWrap{position:relative;width:100%;aspect-ratio:68/100;border-radius:16px;overflow:hidden;border:1px solid rgba(224,244,234,.35);background:#0f5c35;box-shadow:inset 0 0 36px rgba(0,0,0,.18)}.em80Canvas{display:block;width:100%;height:100%;touch-action:none}
  .em80Ticker{min-height:34px;margin-top:8px;padding:8px 10px;border:1px solid #1e3b4d;background:#0b1c27;border-radius:12px;font-size:10px;color:#c5d6df;line-height:1.35}.em80Ticker b{color:#fff}.em80Meta{display:flex;justify-content:space-between;gap:8px;margin:7px 2px 0;font-size:9px;color:#94aab8}.em80Meta b{color:#dce6eb}.em80Actions{margin-top:9px}.em80Actions button{padding:10px 8px}.em80Hint{text-align:center;color:#a8bbc6;font-size:9px;line-height:1.35;margin-top:6px}
  .em80DecisionBoard{margin:10px 0 13px}.em80DecisionBoard .em80CanvasWrap{aspect-ratio:86/58;max-height:238px}.em80DecisionBoard .em80Canvas{width:100%;height:100%}
  @media(max-height:720px){.em80CanvasWrap{max-height:57vh}.em80DecisionBoard .em80CanvasWrap{max-height:185px}}
  `;
  document.head.appendChild(st);
})();

const EM80={raf:0,minuteTimer:0,lastFrame:0,running:false,canvas:null,ctx:null,token:0};
const EM80_W=68,EM80_H=100,EM80_GOAL_HALF=11.5;
function em80Clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function em80Dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function em80Lerp(a,b,t){return a+(b-a)*t}
function em80Dir(team){return team==='us'?-1:1}
function em80Opp(team){return team==='us'?'them':'us'}
function em80BaseSlots(team){
  let raw=team==='us'?(typeof v0712BaseSlots==='function'?v0712BaseSlots():[]):(typeof v0712MirrorSlots==='function'?v0712MirrorSlots():[]);
  return raw.map((q,i)=>({idx:i,x:(q.x||50)*EM80_W/100,y:q.y||50,pos:q.pos||'MC'}))
}
function em80UserLineup(l=S.live){return typeof v0712Lineup==='function'?v0712Lineup(l):bestXI().slice(0,11)}
function em80PlayerQuality(p,kind='ovr'){
  if(!p)return 68;let s=p.skills||{},m=typeof playerCareerMetrics==='function'?playerCareerMetrics(p):{};
  if(kind==='pass')return s.passing||m.decision||p.ovr||68;
  if(kind==='finish')return s.finishing||m.composure||p.ovr||68;
  if(kind==='tech')return s.technique||m.decision||p.ovr||68;
  if(kind==='def')return s.defense||m.decision||p.ovr||68;
  if(kind==='pace')return s.pace||m.physical||p.ovr||68;
  return p.ovr||68
}
function em80SpeedFor(p,pos){let q=em80PlayerQuality(p,'pace');return (pos==='ARQ'?7.6:9.2+(q-60)*.045)}
function em80InitPlayers(l){
  let usSlots=em80BaseSlots('us'),opSlots=em80BaseSlots('them'),xi=em80UserLineup(l),oppR=club(l.opponent).r||70;
  let us=usSlots.map((q,i)=>{let p=xi[i];return{team:'us',idx:i,id:p?.id||('u'+i),name:p?.name||('Jugador '+(i+1)),pos:q.pos,x:q.x,y:q.y,vx:0,vy:0,tx:q.x,ty:q.y,ovr:p?.ovr||68,speed:em80SpeedFor(p,q.pos),brain:0}});
  let them=opSlots.map((q,i)=>({team:'them',idx:i,id:'opp'+i,name:'Rival '+(i+1),pos:q.pos,x:q.x,y:q.y,vx:0,vy:0,tx:q.x,ty:q.y,ovr:oppR,speed:q.pos==='ARQ'?7.5:9.6+(oppR-68)*.035,brain:0}));
  return{us,them}
}
function em80State(l=S.live){
  if(!l)return null;
  if(!l.v0800||!Array.isArray(l.v0800.us)||l.v0800.us.length!==11){
    let ps=em80InitPlayers(l),mid=ps.us.filter(p=>['MCD','MC','MCO'].includes(p.pos))[0]||ps.us[5]||ps.us[0];
    l.v0800={us:ps.us,them:ps.them,ball:{x:mid.x,y:mid.y,vx:0,vy:0,ownerTeam:'us',ownerIdx:mid.idx,lastTeam:'us',flight:null},comment:'Tu equipo pone la pelota en juego y se acomoda.',phase:'Salida',possessionTicks:{us:1,them:0},shots:{us:0,them:0},passes:{us:0,them:0},nextBrainAt:0,lastEventCount:(l.events||[]).length,decision:{count:0,last:-99,next:ri(11,18),min:l.mode==='promotion'?4:(l.mode==='cup'||l.mode==='continental'?3:2),max:l.mode==='promotion'?6:5},restartUntil:0};
  }
  return l.v0800
}
function em80RefreshRoster(l=S.live){let s=em80State(l);if(!s)return;let xi=em80UserLineup(l),reds=new Set(l.redCardIds||[]);s.us.forEach((p,i)=>{let q=xi[i];if(q){p.id=q.id;p.name=q.name;p.ovr=q.ovr||p.ovr;p.speed=em80SpeedFor(q,p.pos);p.active=!reds.has(q.id)}else p.active=false});let oppReds=Math.max(0,(l.oppRedCards||[]).length||0),removed=0;for(let p of [...s.them].reverse()){if(p.pos==='ARQ'){p.active=true;continue}p.active=removed>=oppReds;if(!p.active)removed++}}
function em80Players(team,l=S.live){let s=em80State(l);return team==='us'?s.us:s.them}
function em80P(team,idx,l=S.live){return em80Players(team,l)[idx]||em80Players(team,l)[0]}
function em80BallOwner(l=S.live){let s=em80State(l),b=s.ball;return b.ownerTeam?em80P(b.ownerTeam,b.ownerIdx,l):null}
function em80GoalY(team){return team==='us'?1:99}
function em80OwnGoalY(team){return team==='us'?99:1}
function em80Progress(team,y){return team==='us'?100-y:y}
function em80Zone(team,y){let p=em80Progress(team,y);return p<35?'Salida':p<70?'Progresión':'Último tercio'}
function em80Side(x){let pct=x/EM80_W;return pct<.36?'izquierda':pct>.64?'derecha':'centro'}
function em80Nearest(team,point,l=S.live,filter=null,skip=-1){let arr=em80Players(team,l),best=null,bd=1e9;for(let p of arr){if(p.active===false||p.idx===skip)continue;if(filter&&!filter.includes(p.pos))continue;let d=em80Dist(p,point);if(d<bd){bd=d;best=p}}return{p:best,d:bd}}
function em80SegmentClear(team,a,b,l=S.live){let opp=em80Players(em80Opp(team),l),vx=b.x-a.x,vy=b.y-a.y,ll=vx*vx+vy*vy||1,min=99;for(let o of opp){if(o.active===false)continue;let t=em80Clamp(((o.x-a.x)*vx+(o.y-a.y)*vy)/ll,.08,.92),x=a.x+t*vx,y=a.y+t*vy;min=Math.min(min,Math.hypot(o.x-x,o.y-y))}return min}
function em80SpaceAt(team,point,l=S.live){return em80Nearest(em80Opp(team),point,l).d}
function em80Anchor(team,p,l=S.live){let slots=em80BaseSlots(team),q=slots[p.idx]||{x:34,y:50,pos:p.pos},s=em80State(l),b=s.ball,owner=b.ownerTeam,own=owner===team,dir=em80Dir(team),zone=em80Zone(team,b.y),sameSide=(b.x<EM80_W*.5&&q.x<EM80_W*.5)||(b.x>=EM80_W*.5&&q.x>=EM80_W*.5),ctx=l.context||{},x=q.x,y=q.y;
  if(p.pos==='ARQ'){x=EM80_W/2+(b.x-EM80_W/2)*.11;y=team==='us'?(own&&zone==='Salida'?91:95):(own&&zone==='Salida'?9:5);return{x,y}}
  if(own){
    if(p.pos==='DFC'){y+=dir*(zone==='Salida'?4:zone==='Progresión'?8:11);x=EM80_W/2+(x-EM80_W/2)*(zone==='Salida'?1.18:.98)}
    else if(p.pos==='LI'||p.pos==='LD'){let ov=ctx.fullbacksHigh?5:0;if(sameSide){y+=dir*((zone==='Salida'?8:zone==='Progresión'?16:22)+ov);x=EM80_W/2+(x-EM80_W/2)*1.08}else{y+=dir*(zone==='Salida'?4:zone==='Progresión'?8:11);x=EM80_W/2+(x-EM80_W/2)*.72}}
    else if(p.pos==='MCD'){y=em80Lerp(y+dir*5,b.y-dir*9,.48);x=em80Lerp(x,EM80_W/2+(b.x-EM80_W/2)*.34,.5)}
    else if(p.pos==='MC'){x=em80Lerp(x,sameSide?(b.x<EM80_W/2?Math.min(EM80_W*.46,b.x+9):Math.max(EM80_W*.54,b.x-9)):EM80_W/2+(x-EM80_W/2)*.75,.45);y+=dir*(zone==='Último tercio'?14:9)}
    else if(p.pos==='MCO'){x=em80Lerp(x,EM80_W/2+(b.x-EM80_W/2)*.3,.58);y=em80Lerp(y+dir*12,b.y+dir*10,.42)}
    else if(p.pos==='EI'||p.pos==='ED'){if(sameSide){x=EM80_W/2+(x-EM80_W/2)*1.08;y+=dir*(zone==='Salida'?8:zone==='Progresión'?14:10)}else{x=EM80_W/2+(x-EM80_W/2)*(zone==='Último tercio'?.68:.96);y+=dir*(zone==='Último tercio'?21:15)}}
    else if(p.pos==='DC'){x=em80Lerp(x,EM80_W/2+(b.x-EM80_W/2)*.14,.55);y=em80Lerp(y,b.y+dir*(zone==='Salida'?22:zone==='Progresión'?17:9),.6)}
    if(ctx.lowBlock&&['DFC','LI','LD','MCD'].includes(p.pos))y-=dir*3;
  }else{
    let towardOwn=team==='us'?1:-1,defLine=team==='us'?em80Clamp(b.y+18,63,84):em80Clamp(b.y-18,16,37),shift=em80Clamp((b.x-EM80_W/2)*.32,-7,7);
    if(p.pos==='DFC'){y=defLine;x=EM80_W/2+(x-EM80_W/2)*.85+shift*.3}
    else if(p.pos==='LI'||p.pos==='LD'){y=defLine+towardOwn*1;x=sameSide?em80Lerp(x,b.x,.27):EM80_W/2+(x-EM80_W/2)*.78}
    else if(p.pos==='MCD'){y=defLine+dir*11;x=EM80_W/2+shift*.42}
    else if(p.pos==='MC'){y=defLine+dir*18;x=EM80_W/2+(x-EM80_W/2)*.72+shift*.4}
    else if(p.pos==='MCO'){y=defLine+dir*24;x=EM80_W/2+shift*.45}
    else if(p.pos==='EI'||p.pos==='ED'){y=defLine+dir*(ctx.lowBlock?18:27);x=EM80_W/2+(x-EM80_W/2)*(ctx.lowBlock?.74:.92)+shift*.25}
    else if(p.pos==='DC'){y=defLine+dir*(ctx.pressHigh?30:35);x=EM80_W/2+shift*.18}
  }
  return{x:em80Clamp(x,3.5,EM80_W-3.5),y:em80Clamp(y,3,97)}
}
function em80Targets(l=S.live){let s=em80State(l),b=s.ball,owner=em80BallOwner(l),poss=owner?.team||b.lastTeam||'us';for(let team of ['us','them']){let arr=em80Players(team,l),ch=em80Nearest(team,b,l,['DFC','LI','LD','MCD','MC','MCO','EI','ED','DC']).p;for(let p of arr){if(p.active===false)continue;let t=em80Anchor(team,p,l);if(owner&&owner.team===team&&owner.idx===p.idx){let dir=em80Dir(team),goal={x:EM80_W/2,y:em80GoalY(team)},dx=goal.x-p.x,dy=goal.y-p.y,d=Math.hypot(dx,dy)||1;t={x:p.x+dx/d*4.5,y:p.y+dy/d*4.5}}else if((!owner||poss!==team)&&p===ch&&p.pos!=='ARQ'){let ownGoal={x:EM80_W/2,y:em80OwnGoalY(team)},dx=ownGoal.x-b.x,dy=ownGoal.y-b.y,d=Math.hypot(dx,dy)||1;t={x:b.x+dx/d*.9,y:b.y+dy/d*.9}}p.tx=em80Clamp(t.x,2.8,EM80_W-2.8);p.ty=em80Clamp(t.y,2.5,97.5)}for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){let a=arr[i],c=arr[j];if(a.active===false||c.active===false)continue;let dx=a.tx-c.tx,dy=a.ty-c.ty,d=Math.hypot(dx,dy);if(d>0&&d<3.2){let push=(3.2-d)*.32;a.tx+=dx/d*push;a.ty+=dy/d*push;c.tx-=dx/d*push;c.ty-=dy/d*push}}}}
function em80MovePlayers(dt,l=S.live){em80Targets(l);for(let team of ['us','them'])for(let p of em80Players(team,l)){if(p.active===false)continue;let dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy),max=p.speed*(p.pos==='ARQ'?.72:1);if(d>.03){let want=Math.min(max,d*2.2),ux=dx/d,uy=dy/d,targetVx=ux*want,targetVy=uy*want,blend=Math.min(1,dt*4.2);p.vx=em80Lerp(p.vx,targetVx,blend);p.vy=em80Lerp(p.vy,targetVy,blend)}else{p.vx*=.82;p.vy*=.82}p.x=em80Clamp(p.x+p.vx*dt,2.5,EM80_W-2.5);p.y=em80Clamp(p.y+p.vy*dt,2,98)}}
function em80BestPass(team,carrier,l=S.live,mode='normal'){let mates=em80Players(team,l),dir=em80Dir(team),zone=em80Zone(team,carrier.y),best=null,bs=-1e9;for(let m of mates){if(m.active===false||m.idx===carrier.idx||m.pos==='ARQ'&&zone!=='Salida')continue;let d=em80Dist(carrier,m);if(d<6||d>38)continue;let prog=(m.y-carrier.y)*dir,clear=em80SegmentClear(team,carrier,m,l),space=em80SpaceAt(team,m,l),score=18-Math.abs(d-20)*.45+prog*(mode==='through'?.8:zone==='Salida'?.42:.55)+Math.min(8,clear*1.4)+Math.min(7,space*.8);if(mode==='switch')score+=Math.abs(m.x-carrier.x)*.6;if(mode==='through'&&['DC','EI','ED','MCO'].includes(m.pos))score+=9;if(zone==='Último tercio'&&['DC','MCO','EI','ED'].includes(m.pos))score+=5;if(l.context?.possession)score-=Math.max(0,d-24)*.4;if(l.context?.direct)score+=prog*.2;if(score>bs){bs=score;best=m}}return best}
function em80Comment(txt,l=S.live){let s=em80State(l);s.comment=txt;let e=document.getElementById('em80Ticker');if(e)e.innerHTML=`<b>${l.minute}'</b> ${txt}`}
function em80Flight(kind,team,from,to,duration,outcome=null,extra={},l=S.live){let s=em80State(l),b=s.ball;b.ownerTeam=null;b.ownerIdx=null;b.lastTeam=team;b.flight={kind,team,from:{x:from.x,y:from.y},to:{x:to.x,y:to.y},started:performance.now(),duration,outcome,...extra};b.x=from.x;b.y=from.y}
function em80Pass(team,carrier,target,l=S.live,kind='pass'){let s=em80State(l),clear=em80SegmentClear(team,carrier,target,l),q=team==='us'?em80PlayerQuality(em80UserLineup(l)[carrier.idx],'pass'):(club(l.opponent).r||70),risk=em80Clamp(.035+Math.max(0,3.5-clear)*.035+Math.max(0,em80Dist(carrier,target)-28)*.003+(kind==='through'?.04:0)-(q-65)*.0012,.02,.25),cut=Math.random()<risk;if(cut){let t=.38+Math.random()*.25,pt={x:em80Lerp(carrier.x,target.x,t),y:em80Lerp(carrier.y,target.y,t)},inter=em80Nearest(em80Opp(team),pt,l).p;em80Comment(team==='us'?`${carrier.name.split(' ').slice(-1)[0]} intenta progresar, pero ${inter.pos==='DFC'?'un central rival':'un rival'} lee el pase y lo corta.`:'Tu equipo anticipa el pase rival y recupera.',l);em80Flight('intercept',team,carrier,pt,430,'intercept',{interTeam:em80Opp(team),interIdx:inter.idx},l);return}s.passes[team]++;let lead={x:target.x+target.vx*.12,y:target.y+target.vy*.12};em80Comment(team==='us'?`${carrier.name.split(' ').slice(-1)[0]} ${kind==='through'?'filtra':'juega'} para ${target.name.split(' ').slice(-1)[0]}.`:'El rival mueve la pelota buscando una línea de avance.',l);em80Flight(kind,team,carrier,lead,kind==='through'?500:430,'receive',{recvTeam:team,recvIdx:target.idx},l)}
function em80Carry(team,carrier,l=S.live){let s=em80State(l),goal={x:EM80_W/2,y:em80GoalY(team)},cands=[-0.55,-0.28,0,.28,.55],best=null,bs=-1e9;for(let a of cands){let base=Math.atan2(goal.y-carrier.y,goal.x-carrier.x)+a,pt={x:em80Clamp(carrier.x+Math.cos(base)*6,3,EM80_W-3),y:em80Clamp(carrier.y+Math.sin(base)*6,3,97)},space=em80SpaceAt(team,pt,l),score=space*1.2+em80Progress(team,pt.y)*.08-Math.abs(pt.x-EM80_W/2)*.03;if(score>bs){bs=score;best=pt}}carrier.tx=best.x;carrier.ty=best.y;s.nextBrainAt=performance.now()+650;em80Comment(team==='us'?`${carrier.name.split(' ').slice(-1)[0]} conduce y espera que se abra una línea de pase.`:'El rival conduce; tu bloque retrocede sin romperse.',l)}
function em80Shot(team,carrier,l=S.live){let s=em80State(l),goalY=em80GoalY(team),dist=Math.abs(goalY-carrier.y),pressure=em80Nearest(em80Opp(team),carrier,l).d,q=team==='us'?em80PlayerQuality(em80UserLineup(l)[carrier.idx],'finish'):(club(l.opponent).r||70),anglePenalty=Math.abs(carrier.x-EM80_W/2)/EM80_W,blockLane=em80SegmentClear(team,carrier,{x:EM80_W/2,y:goalY},l),goalP=em80Clamp(.08+(q-62)*.0045+(24-dist)*.006+Math.min(pressure,6)*.012-anglePenalty*.18,.05,.38),blockP=em80Clamp(.10+Math.max(0,3.1-blockLane)*.07,.08,.32),r=Math.random(),out='save';if(r<blockP)out='block';else if(r<blockP+goalP)out='goal';else if(r>0.88)out='wide';let target;if(out==='goal')target={x:EM80_W/2+(Math.random()-.5)*EM80_GOAL_HALF*1.4,y:goalY};else if(out==='wide')target={x:EM80_W/2+(Math.random()<.5?-1:1)*(EM80_GOAL_HALF+4+Math.random()*4),y:goalY};else if(out==='block'){let pt={x:em80Lerp(carrier.x,EM80_W/2,.5),y:em80Lerp(carrier.y,goalY,.5)},d=em80Nearest(em80Opp(team),pt,l,['DFC','LI','LD','MCD']).p;target={x:d.x,y:d.y}}else target={x:EM80_W/2+(Math.random()-.5)*6,y:team==='us'?5:95};s.shots[team]++;if(l.flow){l.flow.userThreat=(l.flow.userThreat||0)*.92+(team==='us'?.55:0);l.flow.oppThreat=(l.flow.oppThreat||0)*.92+(team==='them'?.55:0)}em80Comment(team==='us'?`${carrier.name.split(' ').slice(-1)[0]} encuentra el espacio y patea al arco.`:'El rival consigue sacar el remate.',l);em80Flight('shot',team,carrier,target,out==='block'?330:500,out,{shooterIdx:carrier.idx},l)}
function em80Cross(team,carrier,l=S.live){let box={x:EM80_W/2+(Math.random()-.5)*12,y:team==='us'?13:87},target=em80Nearest(team,box,l,['DC','MCO','EI','ED','MC']).p;em80Comment(team==='us'?`${carrier.name.split(' ').slice(-1)[0]} gana la banda y mete el centro al área.`:'El rival llega por afuera y lanza el centro.',l);em80Flight('cross',team,carrier,box,560,'cross',{recvTeam:team,recvIdx:target.idx},l)}
function em80CarrierThink(l=S.live){let s=em80State(l),b=s.ball;if(!b.ownerTeam||performance.now()<s.nextBrainAt||performance.now()<s.restartUntil)return;let team=b.ownerTeam,c=em80P(team,b.ownerIdx,l),zone=em80Zone(team,c.y),pressure=em80Nearest(em80Opp(team),c,l).d,wide=c.x<EM80_W*.24||c.x>EM80_W*.76,progress=em80Progress(team,c.y),q=team==='us'?em80PlayerQuality(em80UserLineup(l)[c.idx],'finish'):(club(l.opponent).r||70),shotReady=progress>72&&['DC','MCO','MC','EI','ED'].includes(c.pos)&&pressure>1.7;s.nextBrainAt=performance.now()+520+Math.random()*380;if(shotReady&&(l.context?.shootMore||progress>82||Math.random()<.34+(q-70)*.006))return em80Shot(team,c,l);if(zone==='Último tercio'&&wide&&['LI','LD','EI','ED'].includes(c.pos)&&progress>75&&Math.random()<.44)return em80Cross(team,c,l);let mode=(l.context?.direct||pressure<2.6)?'through':(Math.random()<.13?'switch':'normal'),pass=em80BestPass(team,c,l,mode),passGain=pass?(em80Progress(team,pass.y)-progress):-99;if(pass&&(pressure<3.6||passGain>8||l.context?.possession||Math.random()<.68))return em80Pass(team,c,pass,l,mode==='through'?'through':'pass');return em80Carry(team,c,l)}
function em80Restart(team,type='goalKick',l=S.live){let s=em80State(l),arr=em80Players(team,l),gk=arr.find(p=>p.pos==='ARQ')||arr[0],mid=arr.find(p=>p.active!==false&&['MCD','MC'].includes(p.pos))||arr.find(p=>p.active!==false)||arr[0],p=type==='kickoff'?mid:gk;s.ball={x:p.x,y:p.y,vx:0,vy:0,ownerTeam:team,ownerIdx:p.idx,lastTeam:team,flight:null};s.restartUntil=performance.now()+700;s.nextBrainAt=s.restartUntil+250}
function em80FinishFlight(now,l=S.live){let s=em80State(l),b=s.ball,f=b.flight;if(!f)return;let t=em80Clamp((now-f.started)/f.duration,0,1),ease=t*t*(3-2*t);b.x=em80Lerp(f.from.x,f.to.x,ease);b.y=em80Lerp(f.from.y,f.to.y,ease);if(t<1)return;b.flight=null;if(f.outcome==='receive'){let p=em80P(f.recvTeam,f.recvIdx,l);b.x=p.x;b.y=p.y;b.ownerTeam=f.recvTeam;b.ownerIdx=f.recvIdx;b.lastTeam=f.recvTeam;return}if(f.outcome==='intercept'){let p=em80P(f.interTeam,f.interIdx,l);b.x=p.x;b.y=p.y;b.ownerTeam=f.interTeam;b.ownerIdx=f.interIdx;b.lastTeam=f.interTeam;return}if(f.outcome==='cross'){let recv=em80P(f.recvTeam,f.recvIdx,l),opp=em80Nearest(em80Opp(f.team),f.to,l,['DFC','LI','LD']).p,win=(recv.ovr||70)+(Math.random()*18)>(opp.ovr||70)+(Math.random()*18);if(win){b.ownerTeam=f.team;b.ownerIdx=recv.idx;b.x=recv.x;b.y=recv.y;s.nextBrainAt=performance.now()+180}else{b.ownerTeam=opp.team;b.ownerIdx=opp.idx;b.x=opp.x;b.y=opp.y;em80Comment(f.team==='us'?'El central rival gana de arriba y despeja.':'Tu defensa gana el duelo aéreo y saca la pelota.',l)}return}if(f.kind==='shot'){if(f.outcome==='goal'){let teamId=f.team==='us'?S.clubId:l.opponent;teamGoal(teamId,l.minute,'jugada');em80Comment(f.team==='us'?'¡GOL! La jugada termina adentro.':'Gol rival tras la llegada.',l);em80Restart(em80Opp(f.team),'kickoff',l);return}if(f.outcome==='block'){let d=em80Nearest(em80Opp(f.team),f.to,l,['DFC','LI','LD','MCD']).p;b.ownerTeam=d.team;b.ownerIdx=d.idx;b.x=d.x;b.y=d.y;em80Comment(f.team==='us'?'El remate pega en un defensor y la jugada cambia de dueño.':'Tu defensa bloquea el remate.',l);return}if(f.outcome==='save'){let gk=em80Players(em80Opp(f.team),l).find(p=>p.pos==='ARQ');b.ownerTeam=gk.team;b.ownerIdx=gk.idx;b.x=gk.x;b.y=gk.y;em80Comment(f.team==='us'?'El arquero rival contiene el remate.':'Tu arquero se queda con la pelota.',l);return}em80Comment(f.team==='us'?'El remate se va afuera. Saque de arco.':'El rival remata desviado.',l);em80Restart(em80Opp(f.team),'goalKick',l);return}}
function em80BallControl(l=S.live){let s=em80State(l),b=s.ball;if(b.flight||b.ownerTeam)return;let nearest=null,bd=2.2;for(let team of ['us','them'])for(let p of em80Players(team,l)){if(p.active===false)continue;let d=em80Dist(p,b);if(d<bd){bd=d;nearest=p}}if(nearest){b.ownerTeam=nearest.team;b.ownerIdx=nearest.idx;b.lastTeam=nearest.team}}
function em80SyncOwnedBall(l=S.live){let s=em80State(l),b=s.ball;if(b.ownerTeam){let p=em80P(b.ownerTeam,b.ownerIdx,l),dir=em80Dir(b.ownerTeam);b.x=p.x;b.y=p.y+dir*.65}}
function em80Frame(ts){if(!EM80.running||!S.live)return;let l=S.live,s=em80State(l);em80RefreshRoster(l);let dt=Math.min(.05,Math.max(.008,(ts-(EM80.lastFrame||ts))/1000));EM80.lastFrame=ts;em80MovePlayers(dt,l);em80FinishFlight(ts,l);em80BallControl(l);em80SyncOwnedBall(l);em80CarrierThink(l);if(s.ball.ownerTeam)s.possessionTicks[s.ball.ownerTeam]++;em80Draw(EM80.canvas,l);EM80.raf=requestAnimationFrame(em80Frame)}
function em80DrawPitch(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d5b34';ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.028)';for(let i=0;i<10;i+=2)ctx.fillRect(0,i*h/10,w,h/10);ctx.strokeStyle='rgba(235,250,241,.68)';ctx.lineWidth=Math.max(1,w/350);ctx.strokeRect(w*.035,h*.025,w*.93,h*.95);ctx.beginPath();ctx.moveTo(w*.035,h*.5);ctx.lineTo(w*.965,h*.5);ctx.stroke();ctx.beginPath();ctx.arc(w*.5,h*.5,w*.13,0,Math.PI*2);ctx.stroke();for(let top of [true,false]){let y=top?h*.025:h*.975,sy=top?1:-1;ctx.strokeRect(w*.24,top?h*.025:h*.835,w*.52,h*.14);ctx.strokeRect(w*.36,top?h*.025:h*.915,w*.28,h*.06);ctx.beginPath();ctx.arc(w*.5,y+sy*h*.095,w*.004,0,Math.PI*2);ctx.fillStyle='rgba(235,250,241,.8)';ctx.fill();ctx.strokeStyle='rgba(235,250,241,.55)';ctx.strokeRect(w*.42,top?h*.006:h*.974,w*.16,h*.018)}}
function em80Draw(canvas,l=S.live){if(!canvas||!l)return;let s=em80State(l),dpr=Math.min(2,window.devicePixelRatio||1),cssW=canvas.clientWidth||340,cssH=canvas.clientHeight||500,w=Math.max(340,Math.round(cssW*dpr)),h=Math.max(500,Math.round(cssH*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}let ctx=canvas.getContext('2d');em80DrawPitch(ctx,w,h);let X=x=>x/EM80_W*w,Y=y=>y/EM80_H*h;for(let team of ['us','them'])for(let p of em80Players(team,l)){if(p.active===false)continue;let r=Math.max(5,w/43),x=X(p.x),y=Y(p.y);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=team==='us'?'#f3bf4d':'#64a7ff';ctx.fill();ctx.lineWidth=Math.max(1,w/300);ctx.strokeStyle=team==='us'?'#ffe8a8':'#c6deff';ctx.stroke();if(team==='us'){let usr=em80UserLineup(l)[p.idx],no=usr?(typeof squadNumber==='function'?squadNumber(usr):p.idx+1):p.idx+1;ctx.fillStyle='#111820';ctx.font=`${Math.max(7,w/54)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(no),x,y+.3)}}let b=s.ball;ctx.beginPath();ctx.arc(X(b.x),Y(b.y),Math.max(3.2,w/85),0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='#111';ctx.stroke();ctx.beginPath();ctx.arc(X(b.x),Y(b.y),Math.max(1,w/220),0,Math.PI*2);ctx.fillStyle='#222';ctx.fill()}
function em80PossessionPct(l=S.live){let s=em80State(l),a=s.possessionTicks.us,b=s.possessionTicks.them,t=Math.max(1,a+b);return Math.round(a/t*100)}
function em80UpdateHud(l=S.live){let s=em80State(l),m=document.getElementById('em80Minute'),sc=document.getElementById('em80Score'),meta=document.getElementById('em80Meta');if(m)m.textContent=`${l.minute}' · PARTIDO EN JUEGO`;if(sc)sc.textContent=`${l.gh} – ${l.ga}`;if(meta){let owner=s.ball.ownerTeam||s.ball.lastTeam,zone=em80Zone(owner,s.ball.y);meta.innerHTML=`<span><b>${owner==='us'?club(S.clubId).name:club(l.opponent).name}</b> · ${zone}</span><span>Posesión ${em80PossessionPct(l)}% · Remates ${s.shots.us}-${s.shots.them}</span>`}}
function em80CardTick(l=S.live){if(Math.random()>.0045)return;let team=Math.random()<.5?'us':'them',arr=em80Players(team,l).filter(p=>p.active!==false&&p.pos!=='ARQ'),p=arr[Math.floor(Math.random()*arr.length)],teamId=team==='us'?S.clubId:l.opponent;l.events.push({m:l.minute,type:'card',teamId,playerId:team==='us'?p.id:null,txt:`🟨 ${p.name} (${club(teamId).name}) — falta táctica`});em80Comment(`El árbitro amonesta a ${p.name}.`,l)}
function em80ShouldPause(l=S.live){let s=em80State(l),d=s.decision;if(!d||l.scenario||l.minute>=89||d.count>=d.max)return false;let hot=Math.abs(scoreForUser(l)-scoreAgainst(l))<=1&&l.minute>=68,shots=s.shots.us+s.shots.them,force=d.count<d.min&&l.minute>=(d.count===0?24:d.count===1?61:80);if(l.minute<d.next&&!force)return false;if(!force&&Math.random()>(.26+(hot?.16:0)+Math.min(.18,shots*.018)))return false;d.count++;d.last=l.minute;d.next=l.minute+ri(11,18);l.pauseCount=d.count;return true}
const _em80ScenarioBase=makeMatchScenario;
makeMatchScenario=function(idx){let l=S.live,s=l&&em80State(l);if(l&&s){let team=s.ball.ownerTeam||s.ball.lastTeam,zone=em80Zone(team,s.ball.y),side=em80Side(s.ball.x),b=typeof back79==='function'?back79():null;if(team==='us'&&zone==='Último tercio'){if(side!=='centro'&&typeof start79==='function'&&typeof seq79==='function'){start79('wide');return seq79('wide',{back:b})}if(typeof v067OffensiveScenario==='function')return v067OffensiveScenario()}if(team==='them'&&zone==='Último tercio'&&typeof start79==='function'&&typeof seq79==='function'){let key=l.context?.fullbacksHigh?'counterdef':(b&&b.e<58?'tiredwing':'counterdef');start79(key);return seq79(key,{back:b})}if(team==='us'&&zone==='Salida'&&(l.flow?.oppThreat||0)>(l.flow?.userThreat||0)+.4&&typeof start79==='function'&&typeof seq79==='function'){start79('pressout');return seq79('pressout',{back:b})}}return _em80ScenarioBase(idx)};
function em80EmergencyDecision(l=S.live){if(!l)return;openModal(`<div class="liveHead"><div class="row between"><span class="minute">${l.minute}' · INTERVENCIÓN DEL DT</span><span class="pill warn">PARTIDO</span></div><div class="liveScore">${l.gh} – ${l.ga}</div><div class="muted small">${club(l.home).name} · ${club(l.away).name}</div></div>${em80DecisionPitchHtml()}<h2>El partido pide una corrección</h2><p>La jugada se detuvo para que ajustes al equipo.</p><button class="choice" onclick="em80EmergencyChoice('balanced')"><b>Mantener el equilibrio</b><span>El equipo conserva su estructura.</span></button><button class="choice" onclick="em80EmergencyChoice('press')"><b>Subir la presión</b><span>Intentás recuperar más arriba.</span></button><button class="choice" onclick="em80EmergencyChoice('direct')"><b>Atacar más directo</b><span>Buscás llegar antes al área rival.</span></button>`);setTimeout(em80DrawDecision,0)}
function em80EmergencyChoice(k){let l=S.live;if(!l)return;if(k==='press'){l.context.pressHigh=true;l.userAttack+=.008;l.fatigue+=.3}else if(k==='direct'){l.context.direct=true;l.userAttack+=.009;l.userDefense-=.003}else{l.userDefense+=.004}l.decisions.push({m:l.minute,title:'Intervención del DT',choice:k,feedback:'Ajuste aplicado'});l.stopIndex++;l.scenario=null;save();closeModal();runNextStop()}
function em80PauseForDecision(l=S.live){if(!l||l.scenario)return;EM80.running=false;if(EM80.raf){cancelAnimationFrame(EM80.raf);EM80.raf=0}if(EM80.minuteTimer){clearTimeout(EM80.minuteTimer);EM80.minuteTimer=0}try{l.scenario=makeMatchScenario(l.stopIndex);save();renderLiveDecision();setTimeout(()=>{if(S.live?.scenario&&!document.querySelector('#modalRoot .choice'))em80EmergencyDecision(l)},120)}catch(e){console.error('em80 decision',e);l.scenario=null;save();em80EmergencyDecision(l)}}
function em80MinuteTick(token){if(token!==EM80.token||!EM80.running||!S.live)return;let l=S.live,s=em80State(l),from=l.minute||0,to=Math.min(90,from+1);l.minute=to;if(l.flow){l.flow.userThreat=(l.flow.userThreat||0)*.94;l.flow.oppThreat=(l.flow.oppThreat||0)*.94;let own=s.ball.ownerTeam||s.ball.lastTeam,zone=em80Zone(own,s.ball.y);if(zone==='Último tercio'){if(own==='us')l.flow.userThreat+=.11;else l.flow.oppThreat+=.11}}if(typeof v061DrainEnergy==='function')try{v061DrainEnergy(from,to)}catch(e){}if(l.context?.pressHigh)l.fatigue=Math.min(10,(l.fatigue||0)+.035);em80CardTick(l);em80UpdateHud(l);save();if(to===45&&!l.halftimeShown){l.halftimeShown=true;save();em80Stop();return v063RenderHalftime()}if(to<90&&em80ShouldPause(l)){return em80PauseForDecision(l)}if(to>=90){em80Stop();return finishRegulation()}EM80.minuteTimer=setTimeout(()=>em80MinuteTick(token),700)}
function em80Stop(){EM80.running=false;EM80.token++;if(EM80.raf){cancelAnimationFrame(EM80.raf);EM80.raf=0}if(EM80.minuteTimer){clearTimeout(EM80.minuteTimer);EM80.minuteTimer=0}EM80.canvas=null;EM80.ctx=null;EM80.lastFrame=0}
function em80RenderMatch(){let l=S.live;if(!l)return render();if(l.scenario)return renderLiveDecision();let s=em80State(l);em80RefreshRoster(l);em80Stop();let token=EM80.token;document.getElementById('modalRoot').innerHTML=`<div class="modalBg em80MatchBg"><div class="modal"><div class="em80Top"><div><div id="em80Minute" class="em80Minute">${l.minute}' · PARTIDO EN JUEGO</div><div id="em80Score" class="em80Score">${l.gh} – ${l.ga}</div><div class="em80Teams">${club(l.home).name} · ${club(l.away).name}</div></div><span class="em80Mode">MOTOR 2D</span></div><div class="em80CanvasWrap"><canvas id="em80Canvas" class="em80Canvas"></canvas></div><div id="em80Meta" class="em80Meta"></div><div id="em80Ticker" class="em80Ticker"><b>${l.minute}'</b> ${s.comment}</div><div class="em80Actions"><button class="secondary" onclick="em80ManualSubs()">⏸ DT / Cambios</button></div><div class="em80Hint">El partido corre solo. La cancha se congela cuando aparece una intervención del DT.</div></div></div>`;EM80.canvas=document.getElementById('em80Canvas');em80Draw(EM80.canvas,l);em80UpdateHud(l);EM80.running=true;EM80.lastFrame=performance.now();EM80.raf=requestAnimationFrame(em80Frame);EM80.minuteTimer=setTimeout(()=>em80MinuteTick(token),700)}
function em80ManualSubs(){em80Stop();v06OpenSubs()}
function em80DecisionPitchHtml(){return `<div class="em80DecisionBoard"><div class="em80CanvasWrap"><canvas id="em80DecisionCanvas" class="em80Canvas"></canvas></div></div>`}
function em80DrawDecision(){let c=document.getElementById('em80DecisionCanvas');if(c&&S.live)em80Draw(c,S.live)}
v0712StopVisual=em80Stop;
v0712PitchHtml=function(l,compact=false){return compact?em80DecisionPitchHtml():''};
v0712RenderVisual=em80RenderMatch;
v06RenderMatchHub=function(){let l=S.live;if(!l)return render();if(l.scenario)return renderLiveDecision();em80RenderMatch()};
runNextStop=function(){if(S.live)v06RenderMatchHub();else render()};
v063AdvanceUntilDecision=function(){if(!S.live)return render();if(S.live.scenario)return renderLiveDecision();em80RenderMatch()};
v0712ManualSubs=em80ManualSubs;
const _em80DecisionRender=renderLiveDecision;
renderLiveDecision=function(){em80Stop();_em80DecisionRender();setTimeout(em80DrawDecision,0)};
v063ResumeSecondHalf=function(){if(!S.live)return;closeModal();v06RenderMatchHub()};
v061ResumeSecondHalf=v063ResumeSecondHalf;
try{if(S?.live){em80State(S.live);save()}}catch(e){console.error('em80 migration',e)}
