 counterdef:{kind:'seq79',stage:1,t:'Te agarraron con los laterales arriba',d:`${m}' · Perdiste la pelota y el rival ataca el espacio que dejó tu última decisión.`,o:[{t:'Cortar la contra ya',h:'Un defensor sale al duelo antes de que entren al área.',mini:'tackle',ok:'safe',fail:'keeper'},{t:'Replegar y cerrar el centro',h:'Cedés metros para recuperar forma.',end:'reform',e:{def:.012,att:-.004}},{t:'Presionar al portador',h:'Buscás recuperar arriba, pero si sale del primer pase queda campo libre.',mini:'press',ok:'safe',fail:'keeper'}]},
 keeper:{kind:'seq79',stage:2,t:'El rival queda mano a mano',d:`${m}' · La primera cobertura no alcanzó. Ahora el arquero tiene que sostener al equipo.`,o:[{t:'Aguantar hasta el remate',h:'Esperás el último gesto del delantero.',mini:'keeper',save:1},{t:'Achicar rápido',h:'Le quitás ángulo antes de que acomode el cuerpo.',mini:'keeper',save:1},{t:'Cubrir el palo largo',h:'Forzás una definición más cerrada.',mini:'keeper',save:1}]},
 pressout:{kind:'seq79',stage:1,t:'No encontrás una salida limpia',d:`${m}' · El rival aprieta arriba y cada receptor tiene una marca cerca.`,o:[{t:'Salir con dos pases cortos',h:'Hay que encontrar al compañero libre antes de que salte la presión.',mini:'playout',ok:'inside'},{t:'Jugar largo al delantero',h:'Evitás el riesgo cerca del arco y peleás la segunda pelota.',a:'second'},{t:'Cambiar de frente',h:'Intentás llevar la pelota al lado débil de la presión.',mini:'through',ok:'wide'}]},
 tiredwing:{kind:'seq79',stage:1,t:'El rival carga sobre tu lateral cansado',d:`${m}' · ${x.back?.p.name||'Tu lateral'} ya no llega con la misma frescura y lo están atacando seguido.`,o:[{t:'Mandar una cobertura',h:'Un volante se cierra para ayudarlo.',end:'cover',e:{def:.014,fat:1}},{t:'Dejarlo en el duelo',h:'Confiás en que resuelva el mano a mano.',mini:'tackle',ok:'safe',fail:'keeper'},{t:'Bajar toda la banda',h:'Cerrás ese sector y resignás salida.',end:'reform',e:{def:.018,att:-.007}}]},
 safe:{kind:'seq79',stage:9,t:'La jugada quedó controlada',d:`${m}' · Tu equipo recuperó la pelota antes de que el rival entrara al área.`,o:[{t:'Seguir jugando',h:'El partido continúa.',end:'safe'}]},
 first:{kind:'seq79',stage:5,t:'La pelota queda para definir de primera',d:`${m}' · No hay tiempo para acomodarse: el remate tiene que salir ahora.`,o:[{t:'Conectar de primera',h:'El momento del contacto define la jugada.',mini:'first',goal:1},{t:'Asegurar el control',h:'Bajás la pelota, pero la defensa gana tiempo.',a:'shot'}]}
 };return z[k]||z.inside}
function add79(o){let l=S.live,e=o?.e||{};l.userAttack+=e.att||0;l.userDefense+=e.def||0;l.fatigue=Math.max(0,(l.fatigue||0)+(e.fat||0))}
function end79(type='info',title='Jugada terminada',text='La acción se cierra y el partido continúa.',icon='⚽'){let l=S.live,v=s79();if(!l)return;let ch=v?.chain?.choices||[];l.decisions.push({m:l.minute,title:'Secuencia de juego',choice:ch.join(' → ')||title,feedback:text});l.events.push({m:l.minute,type:'decision',txt:`🎮 ${title}`});l.stopIndex++;if(v)v.chain=null;l.scenario=null;save();showConsequence({type,icon,title,text,effects:[],duration:2200,onDone:runNextStop})}
function go79(k){let l=S.live;if(!l)return;let v=s79();l.scenario=seq79(k,{back:back79()});if(v?.chain)v.chain.stage=k;save();renderLiveDecision()}
function foul79(zone,p){let l=S.live,v=s79();v.fouls++;v.lastF=l.minute;let name=p?.name||'Tu jugador';showConsequence({type:'warn',icon:'📣',title:'¡FALTA!',text:zone>=2?`${name} protege cerca del área y el defensor llega tarde. Tenés una pelota parada peligrosa.`:`${name} gana el contacto y tu equipo puede meter la pelota en campo rival.`,effects:[],duration:1800,onDone:()=>{l.scenario={kind:'seq79',stage:6,t:zone>=2?'Tiro libre cerca del área':'Tiro libre desde un costado',d:zone>=2?'La barrera se acomoda. Podés buscar el arco o prolongar la jugada.':'Hay gente entrando al área y también una opción corta.',o:zone>=2?[{t:'Pegarle al arco',h:'Buscás superar la barrera.',mini:'freekick',goal:1},{t:'Jugada corta',h:'Intentás mover a la defensa y entrar tocando.',mini:'playout',ok:'inside'},{t:'Centro al área',h:'Buscás un remate de primera.',mini:'cross',ok:'first'}]:[{t:'Centro al área',h:'Buscás una llegada desde atrás.',mini:'cross',ok:'first'},{t:'Tocar corto',h:'Conservás la posesión y hacés mover la marca.',mini:'playout',ok:'wide'}]};save();renderLiveDecision()}})}
function contact79(zone){let l=S.live,s=l.scenario,v=s79(),p=S.roster.find(x=>x.id===s.playerId)||p79(['EI','ED','MCO','DC'],'technique');tr79('Buscar el contacto');let m=playerCareerMetrics(p),chance=clamp(.44+(m.composure-60)*.002+(p.ovr-65)*.002-(v.fouls||0)*.055,.24,.66);if(Math.random()<chance&&l.minute-v.lastF>5)return foul79(zone,p);end79('warn','NO COBRÓ',`${p.name} busca el contacto, pero el árbitro deja seguir y la posesión se pierde.`,'🟨')}
