function v0714DecisionState(l=S.live){if(!l)return null;if(!l.v0714Decision){let intensity=typeof v062MatchIntensity==='function'?v062MatchIntensity(l):50,regular=l.mode==='league',minimum=l.mode==='promotion'?4:(l.mode==='cup'||l.mode==='continental'?3:2),maximum=l.mode==='promotion'?6:(intensity>=72?5:regular?4:5);l.v0714Decision={count:Math.max(l.pauseCount||0,l.stopIndex||0),next:ri(10,17),last:-99,minimum,maximum}}return l.v0714Decision}
function v0714ShouldPause(l){let d=v0714DecisionState(l);if(!l||!d||l.scenario||l.minute>=89)return false;d.count=Math.max(d.count||0,l.pauseCount||0,l.stopIndex||0);if(d.count>=d.maximum)return false;let intensity=v062MatchIntensity(l),since=l.minute-(d.last||-99),contextHot=Math.abs(scoreForUser(l)-scoreAgainst(l))<=1&&l.minute>=68,threat=Math.max(l.flow?.userThreat||0,l.flow?.oppThreat||0),contextChance=(threat>1.2?.018:0)+(contextHot?.018:0)+(l.fatigue>=3?.008:0),due=l.minute>=d.next,lateGuarantee=(d.count<d.minimum&&l.minute>=(d.count===0?24:d.count===1?60:78));if(since<7&&!lateGuarantee)return false;if(!due&&!lateGuarantee&&Math.random()>=contextChance)return false;d.count++;d.last=l.minute;l.pauseCount=d.count;let cooldown=intensity>=78?ri(8,12):intensity>=58?ri(10,15):ri(13,19);d.next=l.minute+cooldown;return true}
v062ShouldPause=v0714ShouldPause;

const _v0714ScenarioBase=makeMatchScenario;
makeMatchScenario=function(idx){let l=S.live,v=v0714State(l);if(l&&v){let phase=v0714Phase(v.poss,l),side=v0714Side(l),b=typeof back79==='function'?back79():null;if(v.poss==='us'&&phase==='final'&&Math.random()<.62){if(side!=='center'&&typeof start79==='function'&&typeof seq79==='function'){start79('wide');return seq79('wide',{back:b})}if(typeof v067OffensiveScenario==='function')return v067OffensiveScenario()}if(v.poss==='them'&&phase==='final'&&Math.random()<.58&&typeof start79==='function'&&typeof seq79==='function'){let key=l.context?.fullbacksHigh?'counterdef':(b&&b.e<58?'tiredwing':'counterdef');start79(key);return seq79(key,{back:b})}if(v.poss==='us'&&phase==='build'&&(l.flow?.oppThreat||0)>(l.flow?.userThreat||0)+.5&&Math.random()<.55&&typeof start79==='function'&&typeof seq79==='function'){start79('pressout');return seq79('pressout',{back:b})}}return _v0714ScenarioBase(idx)};

v0712RenderVisual=function(){let l=S.live;if(!l)return render();v0712StopVisual();let token=_v0712RunToken,v=v0714State(l);document.getElementById('modalRoot').innerHTML=`<div class="modalBg v0712MatchBg"><div class="modal"><div class="v0712Top"><div><div id="v0712Minute" class="v0712Minute">${l.minute}' · PARTIDO EN JUEGO</div><div id="v0712Score" class="score">${l.gh} – ${l.ga}</div><div class="v0712Teams">${club(l.home).name} · ${club(l.away).name}</div><div id="v0714Phase" class="v0714Phase"><b>${v.poss==='us'?club(S.clubId).name:club(l.opponent).name}</b> · ${v0714PhaseLabel(v.poss,l)}</div></div><span class="v0712LivePill">PARTIDO EN VIVO</span></div>${v0714PitchHtml(l)}<div id="v0712Ticker" class="v0712Ticker">${v0712LastTicker(l)}</div><div class="v0712Actions"><button class="secondary" onclick="v0712ManualSubs()">⏸ DT / Cambios</button></div><div class="v0712Paused">Cada jugador se mueve por su función. El partido se frena solo cuando aparece una decisión para el DT.</div></div></div>`;v0714Motion(l);_v0712MotionTimer=setInterval(v0714Motion,520);_v0712TickTimer=setTimeout(()=>v0712Advance(token),650)};

v0712Advance=function(token){if(token!==_v0712RunToken)return;let l=S.live;if(!l||l.scenario)return;try{let v=v0714State(l);if(v.action?.engineGoal&&Date.now()<v.action.endAt){v0714Motion(l);_v0712TickTimer=setTimeout(()=>v0712Advance(token),360);return}let target=Math.min(90,(l.minute||0)+1);simulateSegment(target);v0714HandleEngineEvents(l);v0712RefreshHud(l);v0714Motion(l);let phase=document.getElementById('v0714Phase');if(phase)phase.innerHTML=`<b>${v.poss==='us'?club(S.clubId).name:club(l.opponent).name}</b> · ${v0714PhaseLabel(v.poss,l)}`;if(l.v067PendingImpact){v0712StopVisual();return v067ShowPendingImpact()}if(target===45&&!l.halftimeShown){l.halftimeShown=true;save();v0712StopVisual();return v063RenderHalftime()}if(target<90&&v0714ShouldPause(l)){l.scenario=makeMatchScenario(l.stopIndex);save();v0712StopVisual();return renderLiveDecision()}if(target>=90){v0712StopVisual();return finishRegulation()}save();_v0712TickTimer=setTimeout(()=>v0712Advance(token),650)}catch(e){console.error('v0714 match simulation',e);v0712StopVisual();try{v063AdvanceUntilDecision()}catch(x){console.error('v0714 fallback',x)}}};

// The fallback path gets the same guarantee, so a visual error can never skip every DT intervention.
v063AdvanceUntilDecision=function(){if(_v063Advancing)return;let l=S.live;if(!l)return render();_v063Advancing=true;try{v061StopClock();_v061ClockPaused=true;while(S.live&&l.minute<90){let target=Math.min(l.minute+1,90);simulateSegment(target);if(!S.live)return;if(l.v067PendingImpact)return v067ShowPendingImpact();if(target===45&&!l.halftimeShown){l.halftimeShown=true;save();return v063RenderHalftime()}if(target<90&&v0714ShouldPause(l)){l.scenario=makeMatchScenario(l.stopIndex);save();return renderLiveDecision()}if(target>=90)return finishRegulation()}}finally{_v063Advancing=false}};

try{if(S?.live){v0714State(S.live);v0714DecisionState(S.live);save()}}catch(e){console.error('v0714 migration',e)}
