name = "el-mister-online"
main = "src/index.js"
compatibility_date = "2026-09-01"

[durable_objects]
bindings = [
  { name = "MATCH_ROOMS", class_name = "MatchRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchRoom"]
