function v078SkipMarketAsk(){let m=v075MarketState();openModal(`<div class="eyebrow">⏭️ SALTAR MERCADO</div><h2>¿Cerrar ahora la ventana?</h2><p>Vas a omitir los días ${m.day<7?`${m.day+1}–7`:'restantes'}. Las negociaciones pendientes caducarán y comenzará la próxima temporada.</p><button class="primary" onclick="v078SkipMarket()">Sí, saltar todo el mercado</button><div style="height:8px"></div><button class="secondary" onclick="closeModal()">Seguir negociando</button>`)}
function v078SkipMarket(){closeModal();let m=v075MarketState();for(let q of m.pending.filter(x=>x.status==='pending'))q.status='expired';m.day=7;m.closed=true;save();showConsequence({type:'info',icon:'⏭️',title:'Mercado finalizado',text:'Saltaste los días restantes. La pretemporada ya puede comenzar.',effects:[],duration:1800,onDone:()=>v075StartNextSeason()})}
function v078AnotherSearch(){let m=v075MarketState();m.targets=[];v075RefreshTargets(true);v075MarketTab='targets';save();render();toast('Nueva búsqueda cargada.')}
const _v078MarketDaysBase=v075RenderMarketDays;
v075RenderMarketDays=function(){let html=_v078MarketDaysBase();let extra=`<div class="content"><div class="card"><div class="sectionTitle">Gestionar el club durante el mercado</div><div class="grid2"><button class="secondary" onclick="view='squad';render()">♟ Ver plantilla</button><button class="secondary" onclick="v078AnotherSearch()">🔎 Otra búsqueda</button></div><div style="height:8px"></div><button class="secondary danger" onclick="v078SkipMarketAsk()">⏭ Saltar mercado</button><div class="small muted center" style="margin-top:9px">Durante estos 7 días podés usar Plantel, Cantera, Entrenamiento, Competiciones, Contrato, Carrera y Online. Lo único bloqueado son los partidos.</div></div></div>`;return html+extra+nav()};
const _v078RenderMarketLockBase=render;
render=function(){if(!S){startFlow();return}if(S.phase==='marketDays'&&view==='market'){root().innerHTML=`<div class="app">${v075RenderMarketDays()}</div>`;return}if(S.phase==='marketSummary'){root().innerHTML=`<div class="app">${v075RenderMarketSummary()}</div>`;return}return _v075RenderBase()};
const _v078NextActionBase=nextAction;
nextAction=function(){if(S?.phase==='promotionPrepare')return{e:'🔥 PROMOCIÓN',t:'Todo se define en un partido',d:'El 3.º enfrenta al 8.º de la división superior. No hay empate posible.',b:'Preparar Promoción',a:'v078PreparePromotion()'};if(S?.phase==='promotionMatch')return{e:'🔥 DÍA DE PROMOCIÓN',t:'Ascenso o permanencia',d:'Partido único, máxima intensidad. Todo lo de la temporada desemboca acá.',b:'Jugar Promoción',a:'v078BeginPromotion()'};if(S?.phase==='marketDays'){let m=v075MarketState();return{e:'MERCADO DE PASES',t:`Día ${m.day} de 7`,d:'El mercado está abierto. Podés seguir usando todo el club; durante estos siete días no hay partidos.',b:'Entrar al mercado',a:"view='market';render()"}}return _v078NextActionBase()};

/* Tarjeta previa real antes de cada minijuego */
let _v078PendingMini=null;
const _v078SkillStart=v06StartSkillGame,_v078LaneStart=v062StartLaneGame,_v078MemoryStart=v062StartMemoryGame,_v078KeeperStart=v062StartKeeperGame;
const _v078ShotStart=typeof v067StartShot==='function'?v067StartShot:null;
function v078MiniIntro(kind,p,choice,source){let meta={skill:{e:kind==='penalty'?'⚽ PENAL':kind==='freekick'?'🎯 TIRO LIBRE':'🔥 DEFINICIÓN',t:kind==='penalty'?'Tenés un penal':kind==='freekick'?'Tiro libre al borde del área':'Quedaste mano a mano',d:'Cuando empiece, frená el indicador dentro de la zona marcada. El objetivo es ejecutar la acción con precisión.'},lane:{e:'⚡ CONTRAATAQUE',t:'Encontrá la línea libre',d:'Cuando empiece, la defensa irá cerrando caminos. Tocá el carril que quede libre antes de que lo cubran.'},memory:{e:'🎯 PELOTA PARADA',t:'Memorizá la zona',d:'Primero vas a ver dónde se prepara el movimiento. Después la marca desaparece y tenés que mandar la pelota al mismo sector.'},keeper:{e:'🧤 MANO A MANO',t:'Leé al delantero',d:'Esperá la señal del remate y tocá rápidamente el sector al que va la pelota para intentar taparla.'},shot:{e:'💥 REMATE',t:'Elegí el instante justo',d:'Cuando empiece, frená el indicador dentro de la zona marcada para conectar un remate limpio.'}};let x=meta[kind==='penalty'||kind==='freekick'||kind==='oneonone'?'skill':kind];_v078PendingMini={kind,pid:p.id,choice,source};openModal(`<div class="eyebrow">${x.e} · ANTES DE JUGAR</div><h2>${x.t}</h2><p>${x.d}</p><div class="notice"><b>Objetivo inmediato:</b> resolver esta jugada a favor de tu equipo.</div><button class="primary" onclick="v078LaunchMini()">Empezar</button>`)}
function v078LaunchMini(){let q=_v078PendingMini;_v078PendingMini=null;if(!q)return;let p=S.roster.find(x=>x.id===q.pid);closeModal();if(!p)return;if(['penalty','freekick','oneonone'].includes(q.kind))return _v078SkillStart(q.kind,p,q.choice);if(q.kind==='lane')return _v078LaneStart(p,q.choice);if(q.kind==='memory')return _v078MemoryStart(p,q.choice,q.source);if(q.kind==='keeper')return _v078KeeperStart(p,q.choice);if(q.kind==='shot'&&_v078ShotStart)return _v078ShotStart(p,q.choice,q.source)}
v06StartSkillGame=function(kind,p,choice){v078MiniIntro(kind,p,choice)};
v062StartLaneGame=function(p,choice){v078MiniIntro('lane',p,choice)};
v062StartMemoryGame=function(p,choice,source='corner'){v078MiniIntro('memory',p,choice,source)};
v062StartKeeperGame=function(p,choice){v078MiniIntro('keeper',p,choice)};
if(_v078ShotStart)v067StartShot=function(p,choice,type){v078MiniIntro('shot',p,choice,type)};

(function(){let st=document.createElement('style');st.textContent='.zone-national .zoneMini{color:#ffd7a3;background:rgba(255,160,70,.10)}.table tr.zone-national td:first-child{box-shadow:inset 4px 0 #ff9f43}.zoneDot.national{background:#ff9f43}';document.head.appendChild(st)})();
