renderSeasonEnd=function(){let pos=tablePos(),div=S.league.div,ct=S.contract,met=objectiveMet(pos,ct.objective),direct=div>1&&pos<=2,releg=div<4&&pos>=9,po=v078PlayoffFor(div,pos),next=v06Qualification(pos,div),dom=v078DomesticCupFor(div,pos),title=direct?'¡Ascenso directo!':po?'La temporada sigue: Promoción':releg?'Descenso directo':'Temporada completada';openModal(`<div class="eyebrow">FIN DE TEMPORADA ${S.season}</div><h2>${title}</h2><p>Terminaste ${pos}º en ${DIV_NAMES[div]}. ${met?'Cumpliste el objetivo de Liga.':'No alcanzaste el objetivo de Liga.'}</p><div class="grid2"><div class="metric"><small>Posición</small><b>${pos}º</b></div><div class="metric"><small>Destino Liga</small><b style="font-size:12px">${direct?'Ascenso directo':po?'Promoción':releg?'Descenso':'Permanece'}</b></div><div class="metric"><small>Próxima copa</small><b style="font-size:12px">${dom?v078CupName(dom):next==='main'?V06_MAIN_CUP:next==='secondary'?V06_SECOND_CUP:'—'}</b></div><div class="metric"><small>Premio ascenso</small><b style="font-size:12px">${direct?money(V078_PRIZES.directPromotion):po?.role==='challenger'?money(V078_PRIZES.promotionPlayoff):'—'}</b></div></div><div style="height:12px"></div><button class="primary" onclick="closeSeason(${met},${direct},${releg})">${po?'Ir a la Promoción':'Continuar al mercado'}</button>`)};
closeSeason=function(met){let pos=tablePos(),oldDiv=S.league.div,direct=oldDiv>1&&pos<=2,releg=oldDiv<4&&pos>=9,po=v078PlayoffFor(oldDiv,pos),nextTier=v06Qualification(pos,oldDiv),domestic=v078DomesticCupFor(oldDiv,pos);closeModal();if(po){S.v078Playoff={...po,pos,season:S.season,met,domestic,nextTier,resolved:false};S.phase='promotionPrepare';save();render();v078PreparePromotion();return}S.reputation=clamp(S.reputation+(met?8:-8)+(direct?12:0)+(releg?-8:0),0,100);S.confidence=clamp(S.confidence+(met?10:-12)+(direct?8:0)+(releg?-10:0),0,100);if(direct){S.career.promotions++;v078AddBudget(V078_PRIZES.directPromotion,'Ascenso directo')}updateWorldDivisions();if(S.confidence<=20){S.phase='fired';S.career.firings++;archiveStint('Despido al final de temporada');save();render();return}v078EnterMarket({season:S.season,pos,oldDiv,nextTier,domestic,met,promo:direct,releg})};

/* Resolver Promoción usando el motor completo de partido */
const _v078FinishLiveBase=finishLiveMatch;
finishLiveMatch=function(){let l=S.live;if(!l)return;if(l.mode!=='promotion'){let snap={mode:l.mode,roundIndex:l.mode==='cup'?S.cup?.roundIndex:null,tier:l.mode==='continental'?S.continental?.tier:null,ccIndex:l.mode==='continental'?S.continental?.roundIndex:null,us:scoreForUser(l),them:scoreAgainst(l),pens:l.pens};_v078FinishLiveBase();v078AwardCompetition(snap);return}let p=S.v078Playoff,us=scoreForUser(l),them=scoreAgainst(l),won=l.pens?l.pens.won:us>them,lowerWon=p.role==='challenger'?won:!won;applyPlayerMatchStats(won?'W':'L');S.lineupIds=[...(l.lineupIds||S.lineupIds)];p.resolved=true;p.userWon=won;p.lowerWon=lowerWon;let promoted=p.role==='challenger'&&won,relegated=p.role==='defender'&&!won;if(promoted){S.career.promotions++;v078AddBudget(V078_PRIZES.promotionPlayoff,'Ascenso por Promoción');S.reputation=clamp(S.reputation+12,0,100);S.confidence=clamp(S.confidence+10,0,100)}else if(relegated){S.reputation=clamp(S.reputation-8,0,100);S.confidence=clamp(S.confidence-10,0,100)}updateWorldDivisions();let oldDiv=p.role==='challenger'?p.lowerDiv:p.upperDiv,nextTier=v06Qualification(p.pos,oldDiv),domestic=v078DomesticCupFor(oldDiv,p.pos);S.lastMatch={mode:'promotion',f:{home:l.home,away:l.away,opponent:l.opponent,isHome:l.isHome},gh:l.gh,ga:l.ga,us,them,result:won?'W':'L',pens:l.pens,events:l.events,decisions:l.decisions,competition:'Promoción'};S.live=null;S.phase='postPromotion';S.v075SeasonTransition={season:S.season,pos:p.pos,oldDiv,nextTier,domestic,met:promoted||p.met,promo:promoted,releg:relegated};save();render();renderMatchResult()};
function v078AwardCompetition(s){if(!S||!s||!['cup','continental'].includes(s.mode))return;let won=s.pens?s.pens.won:s.us>s.them,type=s.mode==='cup'?(S.domesticCupType||'national'):s.tier;if(!V078_PRIZES[type])return;let idx=s.mode==='cup'?s.roundIndex:s.ccIndex,finalIdx=s.mode==='cup'?CUP_ROUNDS.length-1:(type==='main'?V06_MAIN_ROUNDS.length-1:V06_SECOND_ROUNDS.length-1),amount=0,label='';if(idx===finalIdx){amount=won?V078_PRIZES[type].champion:V078_PRIZES[type].runner;label=won?`Campeón de ${v078PrizeName(type)}`:`Subcampeón de ${v078PrizeName(type)}`}else if(idx===finalIdx-1&&!won){amount=V078_PRIZES[type].semi;label=`Semifinalista de ${v078PrizeName(type)}`}if(amount){v078AddBudget(amount,label);S.v078LastPrize={amount,label};save();toast(`${label}: +${money(amount)}`)}}
const _v078MatchResultBase=renderMatchResult;
renderMatchResult=function(){let m=S.lastMatch;if(m?.mode!=='promotion')return _v078MatchResultBase();let f=m.f,pen=m.pens?` <span class="small muted">(pen. ${m.pens.us}-${m.pens.them})</span>`:'';openModal(`<div class="eyebrow">🔥 PARTIDO DE PROMOCIÓN</div><div class="scoreBox"><div class="scoreNames"><span>${club(f.home).name}</span><span>${club(f.away).name}</span></div><div class="score">${m.gh} – ${m.ga}</div>${pen}</div><div class="notice ${m.result==='W'?'':'bad'}"><b>${m.result==='W'?'Ganaste la Promoción.':'Perdiste la Promoción.'}</b> ${S.v078Playoff.role==='challenger'?(m.result==='W'?'El ascenso es tuyo.':'Seguís en la categoría.'):(m.result==='W'?'Mantenés la categoría.':'Descendés.')}</div><button class="primary" onclick="closeModal();renderPost()">Continuar</button>`)};
const _v078PostBase=renderPost;
renderPost=function(){let m=S.lastMatch;if(m?.mode!=='promotion')return _v078PostBase();let promoted=S.v075SeasonTransition?.promo,releg=S.v075SeasonTransition?.releg;openModal(`<div class="eyebrow">PROMOCIÓN RESUELTA</div><h2>${promoted?'¡Ascenso!':releg?'Descenso':'Categoría asegurada'}</h2><p>${promoted?`Ganaste el partido más importante del año y además recibís ${money(V078_PRIZES.promotionPlayoff)} por el ascenso.`:releg?'La derrota te manda a la categoría inferior.':'La Promoción terminó y tu equipo permanece en la división.'}</p><button class="primary" onclick="v078AfterPromotion()">Ir al mercado</button>`)};
function v078AfterPromotion(){closeModal();S.v078Playoff=null;let tr=S.v075SeasonTransition;v078EnterMarket(tr)}

/* Próxima temporada: conservar las clasificaciones ya ganadas */
const _v078StartNextSeasonBase=v075StartNextSeason;
v075StartNextSeason=function(){let tr={...(S.v075SeasonTransition||{})},dom=tr.domestic??v078DomesticCupFor(tr.oldDiv,tr.pos);_v078StartNextSeasonBase();S.domesticCupType=dom;S.cup??=setupCupFor(S.clubId,S.season,S.worldDivs);S.cup.eligible=!!dom;if(!dom){S.cup.alive=false;S.cup.nextWeek=null}else{S.cup.alive=true;S.cup.champion=false;S.cup.roundIndex=3;S.cup.nextWeek=CUP_WEEKS[3];S.cup.opponentId=null;S.cup.history=[]}save();render()};

/* Mercado: libre navegación, plantilla disponible y salto total */
