chooseCupOpponent=function(){if(!S.domesticCupType)return _v078ChooseCupOpponentBase();if(S.cup.opponentId)return S.cup.opponentId;let allowed=S.domesticCupType==='ascenso'?[3,4]:[1,2],pool=CLUBS.filter(c=>c.id!==S.clubId&&allowed.includes(S.worldDivs?.[c.id]||c.div));if(!pool.length)return _v078ChooseCupOpponentBase();if(S.cup.roundIndex>=4)pool.sort((a,b)=>b.r-a.r);let opp=pick((S.cup.roundIndex>=4?pool.slice(0,Math.min(pool.length,12)):shuffle(pool)));S.cup.opponentId=opp.id;save();return opp.id};

/* Promoción 3.º vs 8.º de la categoría superior */
function v078RankedDivision(d){if(S.league?.div===d)return sortedTable().map(x=>x.id);return CLUBS.filter(c=>(S.worldDivs?.[c.id]||c.div)===d).sort((a,b)=>(club(b).r+Math.random()*5)-(club(a).r+Math.random()*5)).map(c=>c.id)}
function v078PlayoffFor(div,pos){if(pos===3&&div>1){let opp=v078RankedDivision(div-1)[7];return{role:'challenger',upperDiv:div-1,lowerDiv:div,opponentId:opp}}if(pos===8&&div<4){let opp=v078RankedDivision(div+1)[2];return{role:'defender',upperDiv:div,lowerDiv:div+1,opponentId:opp}}return null}
function v078PreparePromotion(){let p=S.v078Playoff;if(!p)return;let opp=club(p.opponentId);openModal(`<div class="eyebrow">🔥 PARTIDO DE PROMOCIÓN</div><h2>Noventa minutos por la categoría</h2><p>${club(S.clubId).name} enfrenta a ${opp.name}. ${p.role==='challenger'?'Si ganás, ascendés.':'Si perdés, descendés.'} Es un partido único y no puede terminar empatado.</p><div class="notice warn"><b>Partido de máxima tensión.</b> Habrá más situaciones, presión y decisiones que en una fecha normal.</div><div class="sectionTitle">Formación</div><div class="grid3">${['4-2-3-1','4-3-3','4-4-2'].map(x=>`<button class="tab ${formation===x?'active':''}" onclick="formation='${x}';v078PreparePromotion()">${x}</button>`).join('')}</div><div class="sectionTitle" style="margin-top:14px">Mentalidad</div>${[['Ofensivo','Salir a buscar el ascenso o la permanencia.'],['Equilibrado','Leer el partido sin regalar espacios.'],['Defensivo','Priorizar orden y esperar el momento.']].map(([x,d])=>`<button class="choice ${tacticalChoice===x?'selected':''}" onclick="tacticalChoice='${x}';v078PreparePromotion()"><b>${x}</b><span>${d}</span></button>`).join('')}<button class="primary" onclick="v078ConfirmPromotion()">Confirmar y jugar la Promoción</button>`)}
function v078ConfirmPromotion(){S.tactic=tacticalChoice;S.formation=formation;S.phase='promotionMatch';save();closeModal();render()}
function v078BeginPromotion(){let p=S.v078Playoff;if(!p)return;ensureLineup();let callup=(S.roster||[]).filter(x=>!(x.injuredWeeks>0||x.injuryDays>0)).sort((a,b)=>b.ovr-a.ovr).slice(0,18).map(x=>x.id),opp=p.opponentId,isHome=Math.random()<.5,f={home:isHome?S.clubId:opp,away:isHome?opp:S.clubId,opponent:opp,isHome},av=lineupCareerAverages();S.matchScenarioHistory??=[];S.live={mode:'promotion',home:f.home,away:f.away,opponent:f.opponent,isHome:f.isHome,gh:0,ga:0,minute:0,stopIndex:0,pauseCount:0,nextEligibleMinute:ri(6,10),stops:[],userAttack:0,userDefense:0,fatigue:0,moraleMod:0,events:[],decisions:[],shootoutTakers:[],pens:null,careerAvg:av,flow:{userThreat:0,oppThreat:0,userCards:[],oppCards:[],tempo:2},context:{promotion:true},usedScenarioKeys:[],lineupIds:[...S.lineupIds],startingIds:[...S.lineupIds],subbedOutIds:[],subsUsed:0,subWindows:0,subHistory:[],activeSubWindowMinute:null,halftimeShown:false,callupIds:callup,redCardIds:[],oppRedCards:[],v067RegisteredYellowIds:[]};v061InitMatchEnergy();save();closeModal();v06RenderMatchHub()}
const _v078IntensityBase=v062MatchIntensity;
v062MatchIntensity=function(l){return Math.round(clamp(_v078IntensityBase(l)+(l?.mode==='promotion'?20:0),8,100))};
const _v078ExtraBase=renderExtraTime;
finishRegulation=function(){let l=S.live;if((l.mode==='cup'||l.mode==='continental'||l.mode==='promotion')&&l.gh===l.ga)return renderExtraTime();finishLiveMatch()};
renderExtraTime=function(){let l=S.live;if(l?.mode!=='promotion')return _v078ExtraBase();openModal(`<div class="eyebrow">🔥 PROMOCIÓN · PRÓRROGA</div><h2>No se puede terminar igual</h2><p>Después de 90 minutos están ${l.gh}-${l.ga}. El ascenso o la permanencia se define hoy.</p><button class="choice" onclick="resolveExtra('attack')"><b>Ir a buscarlo</b><span>Asumís riesgos para resolverlo antes de los penales.</span></button><button class="choice" onclick="resolveExtra('balanced')"><b>Seguir equilibrado</b><span>Mantenés el plan y esperás el momento.</span></button><button class="choice" onclick="resolveExtra('pens')"><b>Preparar los penales</b><span>Cuidás piernas y orden para una posible tanda.</span></button>`)};

function v078ApplyWorldChanges(){let groups={1:[],2:[],3:[],4:[]};for(let d=1;d<=4;d++)groups[d]=v078RankedDivision(d);let pp=S.v078Playoff;function forceAt(arr,id,idx){if(!id)return arr;arr=arr.filter(x=>x!==id);arr.splice(Math.min(idx,arr.length),0,id);return arr.slice(0,10)}if(pp){let upperId=pp.role==='challenger'?pp.opponentId:S.clubId,lowerId=pp.role==='challenger'?S.clubId:pp.opponentId;groups[pp.upperDiv]=forceAt(groups[pp.upperDiv],upperId,7);groups[pp.lowerDiv]=forceAt(groups[pp.lowerDiv],lowerId,2)}let nd={...S.worldDivs};for(let d=1;d<=4;d++)groups[d].forEach(id=>nd[id]=d);for(let d=2;d<=4;d++)groups[d].slice(0,2).forEach(id=>nd[id]=d-1);for(let d=1;d<=3;d++)groups[d].slice(-2).forEach(id=>nd[id]=d+1);for(let upper=1;upper<=3;upper++){let lower=upper+1,up8=groups[upper][7],low3=groups[lower][2];if(!up8||!low3)continue;if(pp?.resolved&&upper===pp.upperDiv){if(pp.lowerWon){nd[low3]=upper;nd[up8]=lower}else{nd[up8]=upper;nd[low3]=lower}continue}let a=club(low3).r,b=club(up8).r,lowerWins=Math.random()<clamp(.42+(a-b)*.015,.22,.72);if(lowerWins){nd[low3]=upper;nd[up8]=lower}}S.worldDivs=nd}
updateWorldDivisions=v078ApplyWorldChanges;

function v078EnterMarket(tr){S.v075SeasonTransition=tr;S.week=19;S.phase='marketDays';S.weekFlow=null;S.lastMatch=null;S.pendingJobOffer=null;S.v075Market=null;v075MarketState();v075ProcessDay();view='market';save();render()}
