/* ===== El Míster v0.7.8 · pirámide definitiva, promociones, premios y mercado libre ===== */
const V078_PRIZES={
 main:{champion:12,runner:7,semi:3},secondary:{champion:8,runner:4.5,semi:2},
 national:{champion:6,runner:3,semi:1.5},ascenso:{champion:4,runner:2,semi:1},
 directPromotion:3,promotionPlayoff:2
};
function v078AddBudget(amount,label){if(!amount)return;S.budget=+((S.budget??S.contract?.budget??club(S.clubId).budget)+amount).toFixed(2);S.v078PrizeLog??=[];S.v078PrizeLog.push({season:S.season,label,amount});S.v078PrizeLog=S.v078PrizeLog.slice(-30)}
function v078DomesticCupFor(div,pos){if(div===1&&pos>=5&&pos<=8)return'national';if(div===2&&pos<=4)return'national';if((div===3||div===4)&&pos<=4)return'ascenso';return null}
function v078CupName(type=S.domesticCupType){return type==='ascenso'?'Copa Ascenso':'Copa Nacional'}
function v078PrizeName(type){return type==='main'?V06_MAIN_CUP:type==='secondary'?V06_SECOND_CUP:v078CupName(type)}

/* Clasificación definitiva */
v06Qualification=function(pos,div){if(div!==1)return null;if(pos<=2)return'main';if(pos<=4)return'secondary';return null};
v066ZoneFor=function(div,pos){
 if(div===1){if(pos<=2)return{key:'libertador',label:V06_MAIN_CUP};if(pos<=4)return{key:'regional',label:V06_SECOND_CUP};if(pos<=7)return{key:'national',label:'Copa Nacional'};if(pos===8)return{key:'promo',label:'Copa Nacional · Promoción'};if(pos>=9)return{key:'relegation',label:'Descenso directo'}}
 if(div===2){if(pos<=2)return{key:'direct',label:'Ascenso directo · Copa Nacional'};if(pos===3)return{key:'promo',label:'Promoción ascenso · Copa Nacional'};if(pos===4)return{key:'national',label:'Copa Nacional'};if(pos===8)return{key:'promo',label:'Promoción permanencia'};if(pos>=9)return{key:'relegation',label:'Descenso directo'};return null}
 if(div===3){if(pos<=2)return{key:'direct',label:'Ascenso directo · Copa Ascenso'};if(pos===3)return{key:'promo',label:'Promoción ascenso · Copa Ascenso'};if(pos===4)return{key:'ascenso',label:'Copa Ascenso'};if(pos===8)return{key:'promo',label:'Promoción permanencia'};if(pos>=9)return{key:'relegation',label:'Descenso directo'};return null}
 if(div===4){if(pos<=2)return{key:'direct',label:'Ascenso directo · Copa Ascenso'};if(pos===3)return{key:'promo',label:'Promoción ascenso · Copa Ascenso'};if(pos===4)return{key:'ascenso',label:'Copa Ascenso'};return null}return null
};
v066Legend=function(div){let defs=div===1?[['libertador',V06_MAIN_CUP],['regional',V06_SECOND_CUP],['national','Copa Nacional'],['promo','Promoción'],['relegation','Descenso']]:div===2?[['direct','Ascenso directo'],['national','Copa Nacional'],['promo','Promoción'],['relegation','Descenso']]:div===3?[['direct','Ascenso directo'],['ascenso','Copa Ascenso'],['promo','Promoción'],['relegation','Descenso']]:[['direct','Ascenso directo'],['ascenso','Copa Ascenso'],['promo','Promoción']];return`<div class="zoneLegend">${defs.map(([k,l])=>`<span><i class="zoneDot ${k}"></i>${l}</span>`).join('')}</div>`};
renderTableHtml=function(){let div=S.league.div,sorted=sortedTable(),myPos=sorted.findIndex(r=>r.id===S.clubId)+1,myZone=v066ZoneFor(div,myPos);let rows=sorted.map((r,i)=>{let pos=i+1,z=v066ZoneFor(div,pos),zc=z?` zone-${z.key}`:'';return`<tr class="${r.id===S.clubId?'me':''}${zc}"><td class="pos">${pos}</td><td><div>${club(r.id).name}</div>${z?`<div class="zoneMini">${z.label}</div>`:''}</td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf-r.ga}</td><td><b>${r.pts}</b></td></tr>`}).join('');let note=div===1?'1.º–2.º copa principal · 3.º–4.º segunda copa · 5.º–8.º Copa Nacional · 8.º Promoción · 9.º–10.º descenso.':div===2?'1.º–2.º ascenso directo · 3.º Promoción · 1.º–4.º Copa Nacional · 8.º Promoción · 9.º–10.º descenso.':div===3?'1.º–2.º ascenso directo · 3.º Promoción · 1.º–4.º Copa Ascenso · 8.º Promoción · 9.º–10.º descenso.':'1.º–2.º ascenso directo · 3.º Promoción · 1.º–4.º Copa Ascenso · sin descensos.';return`<div class="card"><div class="eyebrow">${DIV_NAMES[div]}</div><h2 style="margin:5px 0 12px">Tabla</h2>${myZone?`<div class="zoneCurrent">Tu posición actual (${myPos}º): <b>${myZone.label}</b>.</div>`:''}<table class="table"><thead><tr><th>#</th><th>Club</th><th>PJ</th><th>G</th><th>E</th><th>P</th><th>DG</th><th>Pts</th></tr></thead><tbody>${rows}</tbody></table>${v066Legend(div)}<div class="competitionRuleNote">${note}</div></div><div class="card"><div class="sectionTitle">Pirámide de clubes</div><div class="tabs">${[1,2,3,4].map(d=>`<button class="tab ${d===div?'active':''}" onclick="showDivision(${d})">${d}ª</button>`).join('')}</div><div id="divisionList">${divisionListHtml(div)}</div></div>`};

/* Copa doméstica según clasificación de la temporada anterior */
const _v078RenderLeagueBase=renderLeague;
renderLeague=function(){let eligible=!!(S.cup?.eligible&&S.domesticCupType);if(!eligible&&leagueTab==='cup')leagueTab='table';return`${topShell()}<div class="content"><div class="subtabs"><button class="subtab ${leagueTab==='table'?'active':''}" onclick="leagueTab='table';render()">Liga</button>${eligible?`<button class="subtab ${leagueTab==='cup'?'active':''}" onclick="leagueTab='cup';render()">${v078CupName()}</button>`:''}</div>${leagueTab==='cup'&&eligible?renderCupHtml():renderTableHtml()}</div>${nav()}`};
renderCupHtml=function(){let cup=S.cup,h=cup?.history||[],name=v078CupName(),status=cup?.champion?'🏆 Campeón':cup?.alive?`En carrera · ${CUP_ROUNDS[cup.roundIndex]}`:'Eliminado';return`<div class="card"><div class="row between"><div><div class="eyebrow">🏆 ${name.toUpperCase()}</div><h2 style="margin:5px 0">${status}</h2></div><span class="cupBadge">Clasificación por Liga</span></div><div class="notice"><b>Premios:</b> campeón ${money(V078_PRIZES[S.domesticCupType].champion)} · subcampeón ${money(V078_PRIZES[S.domesticCupType].runner)} · semifinalista ${money(V078_PRIZES[S.domesticCupType].semi)}.</div>${cup?.alive?`<div class="notice"><b>Próxima ronda:</b> ${CUP_ROUNDS[cup.roundIndex]} · semana ${cup.nextWeek}</div>`:''}</div><div class="card"><div class="sectionTitle">Tu recorrido</div>${h.length?h.map(x=>`<div class="cupLine"><div class="cupRound">${x.round}</div><div class="grow"><b>${x.us}–${x.them} vs ${club(x.opp).name}</b><div class="muted small">${x.outcome}${x.pens?' · penales':''}</div></div></div>`).join(''):'<div class="muted small">Todavía no jugaste partidos de Copa.</div>'}</div>`};

const _v078ChooseCupOpponentBase=chooseCupOpponent;
